### PR TITLE
Upgrade JavaCPP to just released version 1.5.4

### PR DESCRIPTION
**Pull request by saudet**

### CODE REVIEW

**Review by karllessard — APPROVED** [review]

**Comment by karllessard** [comment]
@saudet , any idea how we can fix the build? There is a recurrent Cuda package error now on the GPUs platforms.

**Comment by saudet** [comment]
Looks like the CUDA Docker images from NVIDIA are broken? We might want to switch to some other way of installing CUDA...

**Comment by karllessard** [comment]
Just out of curiosity, I'll try to build on top of Cuda 10.2 docker image to see if that works...

**Comment by karllessard** [comment]
Mmh, worked on Cuda 10.2... https://github.com/tensorflow/java/runs/1101759245?check_suite_focus=true

 I don't know if we can have issues at runtime, but according to @frankfliu, it will fallback anyway looking for Cuda 10.1 so this should be impact-less to our users. Should I commit?

**Comment by saudet** [comment]
No, it's probably not going to work with either CUDA 10.1 or 10.2...

**Pull request merged**
