### PR TITLE
Generic cleanup Metrics and Losses

### PR DESCRIPTION
**Pull request by JimClarke5**
This PR effects both `losses` and `metrics`.

This PR cleans up generic parameters to cut down on the number of unique parameters to at most 1 where possible.
For example:
`public abstract class Metric<U extends TNumber, T extends TNumber> {`
becomes
`public abstract class Metric<T extends TNumber> {`

and

```
@Override
  public <V extends TNumber> List<Op> updateStateList(Operand<U> values, Operand<V> sampleWeights) {
```
Changes to:
```
 public List<Op> updateStateList(
      Operand<? extends TNumber> values, Operand<? extends TNumber> sampleWeights) 
```

### CODE REVIEW

**Comment by JimClarke5** [comment]
@karllessard @Craigacp @rnett  Could one of you clue me in what went wrong here. I rebased the project to the latest `master`, but it still seem to pick up a lot of the commits from the `metrics1` branch, that were applied with yesterday's merge.

**Comment by rnett** [comment]
Only time I've seen that happen is when I didn't update my local `master`, or I had a commit in my branch (that wasn't in master) from before master's latest commit.

Can you cherry pick the commits you want to a new branch?

**Comment by JimClarke5** [comment]
I found this article which sort of explains how to do it. Seems overly complicated.
[How to Fix Your Git Branches After a Rebase](https://www.viget.com/articles/how-to-fix-your-git-branches-after-a-rebase/)

**Comment by Craigacp** [comment]
I second Ryan's suggestion of `git cherry-pick`. Make a new branch from master, run cherry pick giving it the commits that should be in this PR, then force push that branch over this one (or make a new pr from the new branch).

There are other ways to fix it, but it depends on what the exact state of your git repo is.

**Comment by JimClarke5** [comment]
Should I fix this PR? I assume cancel/replace.

**Comment by Craigacp** [comment]
A force push will fix it, but it'll require a bit of a renaming dance with the branches (i.e. cherry-pick to new branch, delete old branch, rename new branch to old branch, force push). It's up to you whichever you find easiest.

**Comment by JimClarke5** [comment]
Rebuilt the branch to exclude commits already included in `master`.

**Pull request closed without merging**
