### PR TITLE
Don't dealloc strings if the TensorBuffer is shared (#357)

### PR DESCRIPTION
**Pull request by brychcy**

### CODE REVIEW

**Comment by saudet** [comment]
There's no more straightforward way to get the information? It doesn't sound like TF_TensorMaybeMove() is always going to return null when the content is being shared.

**Comment by brychcy** [comment]
> There's no more straightforward way to get the information? It doesn't sound like TF_TensorMaybeMove() is always going to return null when the content is being shared.

If there is, I haven't found it.

BTW, what I really wonder is: Shouldn't string deallocation be done automatically on the native Tensorflow level when the last tensor that uses the TensorBuffer is released?

**Comment by saudet** [comment]
No, that doesn't happen. We need to allocate the strings manually, and deallocate them manually or we end up with memory leaks, see issue #251.

**Review by karllessard — APPROVED** [review]
Even if we are not 100% sure that this fix will cover all cases, it seemed to work for @brychcy so let's merge it to give it a try and see. Thanks @brychcy !

**Comment by karllessard** [comment]
Oops, it looks like the modified code is not formatted correctly, @brychcy  can you please run `mvn spotless:apply` locally before pushing a newer version of this PR?

**Comment by brychcy** [comment]
> Oops, it looks like the modified code is not formatted correctly, @brychcy can you please run `mvn spotless:apply` locally before pushing a newer version of this PR?

Done.

At first it didn't do anything for me because origin/master pointed to my version and 
<ratchetFrom>origin/master</ratchetFrom>
is used.

As the whole file was reformatted, I have done it in a separate commit.

**Review by karllessard — APPROVED** [review]
Thanks a lot @brychcy for fixing this!

**Pull request merged**
