### PR TITLE
linux-arm64: add build support for native and framework jars

### PR DESCRIPTION
**Pull request by snadampal**
TensorFlow v2.16.1 wheel artifacts are added
new dependencies are added for native jars
and made sure all unit tests passed.

### CODE REVIEW

**Comment by snadampal** [comment]
Hi @saudet , appreciate your review on this PR.

**Review by Craigacp — APPROVED** [review]
LGTM assuming @saudet thinks the OpenMP linking on Linux arm is fine.

**Comment by snadampal** [comment]
thanks, @Craigacp . OpenMP is a dependency for TensorFlow official wheel on aarch64 linux.

**Review by saudet — APPROVED** [review]

**Comment by snadampal** [comment]
thanks for merging the PR!

**Pull request merged**
