### PR TITLE
Use OP_NAME constant instead of hard coding

### PR DESCRIPTION
**Pull request by rnett**
Simple fix for op generation, results in lots of changed files.

### CODE REVIEW

**Comment by karllessard** [comment]
Ok @rnett , I would really like to simplify the review process to speed up PR merging. In this PR, it looks like 99% of the changes are reformatting again. So here's what I propose:

1. you push your changes without reformatting (disable the plugin and the IDE auto-reformat)
2. I approve (eventually) the PR
3. you just run the formatter plugin goal and push a new version
4. We merge it

Let's experiment this out, wdyt?

**Comment by rnett** [comment]
Ok, I pushed format-less changes.  I'll do the formatting and op generation once you approve it.

**Review by karllessard — DISMISSED** [review]
Great, I love the size of it now, so simple! :D 

Ok to push now new changes that only includes reformatting and regenerated ops, thanks! 👍

**Comment by rnett** [comment]
Op generation is done.

**Comment by karllessard** [comment]
@rnett sorry but I think you'll need to rebase again, since we've merged TF2.5 not long ago

**Comment by rnett** [comment]
@karllessard it's rebased.

**Review by karllessard — APPROVED** [review]

**Pull request merged**
