### PR TITLE
increase max num of outputs

### PR DESCRIPTION
**Pull request by roywei**
fix https://github.com/tensorflow/java/issues/45

@karllessard @saudet @frankfliu

### CODE REVIEW

**Comment by roywei** [comment]
@googlebot I signed it!

**Comment by karllessard** [comment]
Thanks @roywei , can you explain what is the use case of having 1000 outputs in a single op? Is this a custom op?

I agree that 8 is very conservative and should be increased but we should try to limit this number to something reasonable since it has impact on the amount of memory allocated by TF to [return the tensor handles.](https://github.com/tensorflow/java/blob/78f84c08bff9126f90cf6e123283f80450513d75/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerOperationBuilder.java#L270)

**Comment by saudet** [comment]
> I agree that 8 is very conservative and should be increased but we should try to limit this number to something reasonable since it has impact on the amount of memory allocated by TF to [return the tensor handles.](https://github.com/tensorflow/java/blob/78f84c08bff9126f90cf6e123283f80450513d75/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerOperationBuilder.java#L270)

That's just 8 bytes for each pointer, so 8000 bytes for 1000 of them, not exactly a lot of memory.

**Comment by roywei** [comment]
In one of [DJL's](https://djl.ai) NLP applications, we'd like to process a batch of data, sometime it require us to unbatch the data (split by batch size), apply the process (padding for example), and then batch them back together. Here is a [unit test ](https://github.com/awslabs/djl/blob/4353cb34e4f9ba4c281327ad3b887eaa61197648/integration/src/main/java/ai/djl/integration/tests/translate/PaddingStackBatchifierTest.java#L26)with small batch size. For actual NLP use cases, sometimes the actual batch size could be quite big.

So split a batch data (256, 224, 224) into 256 slices of (1,224,224) will return an iterable of size 256 and currently is limited by 8.

**Comment by karllessard** [comment]
@roywei oh I see, an iterable output, that's right. Ok, let's try it out, thanks!

**Pull request merged**
