### PR TITLE
activations, constraints, initializers, losses, regularizers: move Ops param from CTOR to call method

### PR DESCRIPTION
**Pull request by JimClarke5**
This PR moves the `Ops` parameter out of the class `CTOR`s into their respective `call` methods. Also, an interface was created for each package for the respective `call` method.  These packages were chosen because they are stateless wrt the Graph (e.g. no  `Variables`).

There is no change in functionality of these classes, just the move of the `Ops` parameter to `call`.

This is related to issue: #327

### CODE REVIEW

**Review by karllessard — DISMISSED** [review]

**Comment by karllessard** [comment]
Will merge after #331, if the quick-build passes.

**Comment by karllessard** [comment]
@JimClarke5 , can you rebase your PR so that we can validate now that the quick-build is passing?

**Comment by JimClarke5** [comment]
@karllessard I think I have rebased it. Give it a try.

**Comment by karllessard** [comment]
It failed again, looks like it’s the javadoc trouble that is back :-| 

If I remember correctly, the fix for that was to enforce building in Java8, that has not changed as far as I know

**Comment by karllessard** [comment]
I see that you merged master to your branch, I don’t think that’s the issue but rebasing is always better. You can drop your last commit (the merge one) and retry with `git rebase`?

**Comment by karllessard** [comment]
Oh wait, in fact, these javadoc errors are real errors this time :)

Can you please fix them and push a new version?

**Comment by JimClarke5** [comment]
@karllessard @rnett The "check format" is erroring on lines between imports. I ran `google-java-format` against all my files so I don't understand why this is happening.

**Comment by karllessard** [comment]
The way to reformat now is to run `mvn spotless:apply`, can you give it a try?

**Comment by JimClarke5** [comment]
@karllessard I did the `mvn spotless:apply`,  looks check-format passed this time.

**Review by karllessard — APPROVED** [review]

**Pull request merged**
