### PR TITLE
Adding casts to the if test so it passes on GPU

### PR DESCRIPTION
**Pull request by Craigacp**
`ops.math.neg` causes eigen to segfault on GPUs now we've upgraded to TF 2.15. This PR fixes the one test where we do that so that there are casts around it. Not sure how to indicate that users shouldn't use this op on GPU as the op definition accepts ints and it's autogenerated.

### CODE REVIEW

**Comment by karllessard** [comment]
Was this reported to TF core? Or is it an eigen problem?

**Comment by karllessard** [comment]
As we plan to upgrade to TF2.16, let see if the bug is still there before merging this

**Comment by Craigacp** [comment]
The if test still fails on GPU with TF 2.16 (#531).

**Review by karllessard — APPROVED** [review]
Ideally we would wrap this `.neg` operation with our own that would take care of the casting. But let's merge it so at least the build won't fail on GPUs.

**Pull request merged**
