### PR TITLE
Add Initializers

### PR DESCRIPTION
**Pull request by JimClarke5**
I have added Initializers as defined in Keras. The main interface is `Initializer`, the base class is `BaseInitializer`.
Unit tests are included.

This PR is independent of other PRs currently opened.

Some of the initializers, require both a generic for `TType`, and one for `TNumber`, while the `Initializer` interface itself only needs  `TType`. This is because some initializers are more specific in that they only permit numbers, or even just floating types. 
For example, Constant is defined as `Constant<T extends TType>`, because a Constant can take any type.  On the other hand,,  `VarianceScaling`, and all its subclasses, are defined as `VarianceScaling<T extends TType, U extends TNumber>`, because it can only allows floating type. Perhaps there is a better way to do this.

### CODE REVIEW

**Comment by Craigacp** [comment]
Could you rebase this on top of master now the optimizers PR has been merged in? It'll make it a lot easier to review as I suspect the number of files will be much much smaller.

**Comment by JimClarke5** [comment]
I thought I did this before creating the PR, but..

I just did this, let me know if I am missing something:

```
git rebase origin/Initializers origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded origin/master to origin/Initializers.
```

See if that helps

**Comment by Craigacp** [comment]
> I thought I did this before creating the PR, but..
> 
> I just did this, let me know if I am missing something:
> 
> ```
> git rebase origin/Initializers origin/master
> First, rewinding head to replay your work on top of it...
> Fast-forwarded origin/master to origin/Initializers.
> ```
> 
> See if that helps

Hmm, I would have expected it to be `git rebase master Initializers` to replay the top of Initializers on top of master. Either way, it still says this PR touched 1237 files as it's catching the update to the ops generator from the earlier PR. I think this PR should have many fewer files touched in it right?

**Comment by JimClarke5** [comment]
I did `git rebase master Initializers` yesterday before submitting the PR. I could remove this PR and the Initializers branch and  start over easy enough. I am not sure why its picking up the ops generator again. I did not touch that.

**Comment by karllessard** [comment]
> I did `git rebase master Initializers` yesterday before submitting the PR. I could remove this PR and the Initializers branch and start over easy enough. I am not sure why its picking up the ops generator again. I did not touch that.

Maybe you didn't `git fetch` the last version of `origin` after we've merged your previous PR to `master`?

**Comment by JimClarke5** [comment]
I tried all these suggestions but it still show the Ops commits, it will be easier for me to  cancel this PR and replace the branch with a new one.

**Pull request closed without merging**
