### PR TITLE
Interface should be public for external usage

### PR DESCRIPTION
**Pull request by nfeybesse**

### CODE REVIEW

**Comment by Craigacp** [comment]
@nfeybesse once you've signed the CLA we can run the CI and get this merged in.

**Comment by nfeybesse** [comment]
Hello, I signed the CLA yesterday normally

**Comment by karllessard** [comment]
Hey @nfeybesse ,  you got some spotless checks errors being raised by the CI/CD. It is possible that you are not the author of the errors, though as soon as a file is touched and has never been scanned before with spotless, errors are raised.

Can you please run `mvn spotless:apply` at the root of your project and push the changes?

**Comment by nfeybesse** [comment]
I seem to have already done this, the command was executed successfully and nothing was modified. I will confirm tomorrow

**Comment by karllessard** [comment]
> I seem to have already done this, the command was executed successfully and nothing was modified. I will confirm tomorrow

I can already see a few non-compliant syntax, including missing spaces, missing braces, etc. Something you can do to help is to enable the Google Java Format in your IDE (if it is IntelliJ, there is a plugin for that).

**Comment by Craigacp** [comment]
Thanks!

**Pull request merged**
